# name: Deploy on Production
# on:
#   push:
#     branches:
#       - main
# jobs:
#   laravel-config:
#     name: Config Laravel
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3

#     - name: Install Dependencies
#       run: composer install --optimize-autoloader --no-dev

#     - name: Generate key
#       run: php artisan key:generate

#     - name: Optimizing Configuration Loading
#       run: php artisan config:cache

#     - name: Optimizing Route Loading
#       run: php artisan route:cache
